@VibeTree_HostAddress = https://localhost:7115


POST {{VibeTree_HostAddress}}/user/create
Content-Type: application/json
{
     name:"Elvis",
     password:"elvis0130",
     email:"elvis@gmail.com"
}

###

GET {{VibeTree_HostAddress}}/auth/login
Content-Type: application/json
{
    "password":"elvis0130",
    "email":"elvissantanaguimaraes@gmail.com"
}
